/**
 * Autogenerated by Thrift Compiler (0.8.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef pyload_CONSTANTS_H
#define pyload_CONSTANTS_H

#include "pyload_types.h"



class pyloadConstants {
 public:
  pyloadConstants();

};

extern const pyloadConstants g_pyload_constants;



#endif
